package inspecter.expert;

import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import org.jpl7.Atom;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;

/**
 *
 * @author Alphonse
 */
public class Main extends javax.swing.JFrame {

    // Function to remove duplicates from an ArrayList
    public static <T> ArrayList<T> removeDuplicates(ArrayList<T> list) {
        // Create a new LinkedHashSet
        Set<T> set = new LinkedHashSet<>();

        // Add the elements to set
        set.addAll(list);

        // Clear the list
        list.clear();

        // add the elements of set
        // with no duplicates to the list
        list.addAll(set);

        // return the list
        return list;
    }

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(rad_non);
        bg.add(rad_oui);

        this.setResizable(rootPaneCheckingEnabled);

        //setBackground(new Color(0, 0, 0, 0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_vict = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_vol = new javax.swing.JTextField();
        date_vole = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_pers = new javax.swing.JTextField();
        txt_localisation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date_localisation = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txt_persJaloux = new javax.swing.JTextField();
        rad_oui = new javax.swing.JRadioButton();
        rad_non = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        btn_verifier = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_fait = new javax.swing.JTextArea();
        btn_clear = new com.k33ptoo.components.KButton();
        btn_ok = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        header1 = new inspecter.expert.Header();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "A propos du vole", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 0, 24))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setText("Nom victime ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 90, 18);
        jPanel1.add(txt_vict);
        txt_vict.setBounds(116, 40, 230, 30);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Lieu vole");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 90, 72, 18);
        jPanel1.add(txt_vol);
        txt_vol.setBounds(116, 80, 230, 30);
        jPanel1.add(date_vole);
        date_vole.setBounds(116, 130, 230, 30);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel5.setText("Date vole");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 130, 80, 18);

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 410, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faits sur la personne concernnée", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 0, 24))); // NOI18N
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel6.setText("Nom personne");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 60, 95, 18);
        jPanel2.add(txt_pers);
        txt_pers.setBounds(130, 50, 226, 30);
        jPanel2.add(txt_localisation);
        txt_localisation.setBounds(130, 100, 226, 30);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel7.setText("Se trouve");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 110, 61, 18);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel8.setText("Le");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 160, 82, 18);
        jPanel2.add(date_localisation);
        date_localisation.setBounds(130, 150, 230, 30);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel9.setText("Jaloux");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 190, 41, 18);
        jPanel2.add(txt_persJaloux);
        txt_persJaloux.setBounds(130, 190, 230, 30);

        rad_oui.setText("Oui");
        rad_oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_ouiActionPerformed(evt);
            }
        });
        jPanel2.add(rad_oui);
        rad_oui.setBounds(130, 220, 42, 20);

        rad_non.setText("Non");
        jPanel2.add(rad_non);
        rad_non.setBounds(200, 220, 46, 20);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel10.setText("San argeant");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 220, 78, 18);

        btn_verifier.setText("Analyser");
        btn_verifier.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_verifier.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        btn_verifier.setkEndColor(new java.awt.Color(0, 153, 51));
        btn_verifier.setkHoverEndColor(new java.awt.Color(0, 153, 51));
        btn_verifier.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        btn_verifier.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        btn_verifier.setkSelectedColor(new java.awt.Color(204, 204, 255));
        btn_verifier.setkStartColor(new java.awt.Color(204, 204, 255));
        btn_verifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verifierActionPerformed(evt);
            }
        });
        jPanel2.add(btn_verifier);
        btn_verifier.setBounds(490, 250, 110, 30);

        txt_fait.setColumns(20);
        txt_fait.setRows(5);
        txt_fait.setBorder(javax.swing.BorderFactory.createTitledBorder("Fait"));
        jScrollPane2.setViewportView(txt_fait);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(370, 50, 340, 190);

        btn_clear.setText("Nouveau");
        btn_clear.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_clear.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        btn_clear.setkEndColor(new java.awt.Color(0, 153, 51));
        btn_clear.setkHoverEndColor(new java.awt.Color(0, 153, 51));
        btn_clear.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        btn_clear.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        btn_clear.setkSelectedColor(new java.awt.Color(204, 204, 255));
        btn_clear.setkStartColor(new java.awt.Color(204, 204, 255));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear);
        btn_clear.setBounds(260, 250, 90, 30);

        btn_ok.setText("Ok");
        btn_ok.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_ok.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        btn_ok.setkEndColor(new java.awt.Color(0, 153, 51));
        btn_ok.setkHoverEndColor(new java.awt.Color(0, 153, 51));
        btn_ok.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        btn_ok.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        btn_ok.setkSelectedColor(new java.awt.Color(204, 204, 255));
        btn_ok.setkStartColor(new java.awt.Color(204, 204, 255));
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ok);
        btn_ok.setBounds(150, 250, 90, 30);

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 730, 300));
        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));
        kGradientPanel1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jScrollPane3.setViewportView(jEditorPane1);

        kGradientPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 180, 130));

        kGradientPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(102, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inspecter/icon/logo.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inspecter/icon/isp.png"))); // NOI18N

        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inspecter/icon/search_in_list_24px.png"))); // NOI18N
        kButton1.setText("Arbre de recherche");
        kButton1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        kButton1.setkEndColor(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverColor(new java.awt.Color(0, 51, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        kButton1.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton1.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton1.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inspecter/icon/file_24px.png"))); // NOI18N
        kButton2.setText("Fichier prolog");
        kButton2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        kButton2.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverColor(new java.awt.Color(0, 51, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        kButton2.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton2.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton2.setkStartColor(new java.awt.Color(204, 204, 255));

        kButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inspecter/icon/shutdown_24px.png"))); // NOI18N
        kButton3.setText("Fermer");
        kButton3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        kButton3.setkBackGroundColor(new java.awt.Color(204, 204, 255));
        kButton3.setkEndColor(new java.awt.Color(204, 204, 255));
        kButton3.setkHoverColor(new java.awt.Color(0, 51, 0));
        kButton3.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        kButton3.setkIndicatorColor(new java.awt.Color(204, 204, 255));
        kButton3.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton3.setkStartColor(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verifierActionPerformed
        System.out.print(!txt_fait.getText().equals(null));

        if (!txt_fait.getText().equals(null)) {
            try {

                SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
                String date_vol = dcn.format(date_vole.getDate());
                String lieu_vole = txt_localisation.getText();
                String jaloux = txt_persJaloux.getText();
                FileWriter fr = new FileWriter("Inspecteur.pl");
                
                
                fr.write(txt_fait.getText());
                
                if (rad_oui.isSelected()) {
                    fr.write(txt_fait.getText() + "suspect(X):-se_trouve(X," + lieu_vole + "," + date_vol + "),(jaloux(X," + jaloux + ");sans_argeant(X)).");
                }
                if (rad_non.isSelected()) {
                    // fr.write("suspect(X):-se_trouve(X,"+lieu_vole+","+date_vol+"),(jaloux(X,"+jaloux+"). ");
                    fr.write(txt_fait.getText() +"suspect(X):-se_trouve(X," + lieu_vole + "," + date_vol + "),(jaloux(X," + jaloux + ")).");
                }
                fr.close();
                Query qr = new Query("consult", new Term[]{new Atom("Inspecteur.pl")});
                System.out.println("Connexion" + (qr.hasSolution() ? "reussi" : "error"));
                Variable X = new Variable("X");
                Query q1 = new Query("suspect", new Term[]{X});
                Map<String, Term>[] solution;

                solution = q1.allSolutions();
                System.out.println("HAS SOLUTION " + q1.hasSolution());

                if (q1.hasSolution()) {
                    Message m = new Message(this, rootPaneCheckingEnabled);
                    String mes = "";
                    for (int i = 0; i < solution.length; i++) {
                        
                        mes += solution[i].get("X") + " est un voleur \n";
                    }
                    Message.jTextArea1.setText(String.valueOf(mes));
                    m.setVisible(true);
                } else {
                    ArrayList result = new ArrayList();
                    for (Map<String, Term> s : solution) {
                        result.add(s.get("X"));
                    }
                    ArrayList farany = removeDuplicates(result);
                    System.out.println("RESULT " + farany);
                    Message m = new Message(this, rootPaneCheckingEnabled);
                    String mes = "";
                    for (int i = 0; i < farany.size(); i++) {

                        mes += farany.get(i) + " est un voleur \n";
                    }
                    Message.jTextArea1.setText(String.valueOf(mes));

                    m.setVisible(true);
                    /*
                Message m = new Message(this, rootPaneCheckingEnabled);
                Message.resultat_final.setText(txt_pers.getText()+" n'est pas un voleur");
                m.setVisible(true);*/
                }
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        /*
        %fait
        victime(marie,paris,01-09-2022).
        se_trouve(tom,paris,01-09-2022).
        jaloux(tom,marie).
        sans_argeant(tom).

        %regle
        suspect(X):-se_trouve(X,paris,01-09-2022),(jaloux(X,mari);sans_argeant(X)).
        
         */
    }//GEN-LAST:event_btn_verifierActionPerformed

    private void rad_ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_ouiActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        
        String txt_persone = txt_pers.getText();
        String lieu_persone = txt_localisation.getText();
        String nom_vict = txt_vict.getText();
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        String date_loc = dcn.format(date_localisation.getDate());
        String txt_jalou = txt_persJaloux.getText();

        String code = "se_trouve(" + txt_persone + "," + lieu_persone + "," + date_loc + "). \n"
                + "jaloux(" + txt_persone + "," + txt_jalou + "). \n"
                + "sans_argeant(" + txt_persone + ").\n";

        if (rad_oui.isSelected()) {
            if (!txt_fait.equals("")) {
                String valeur_fait = txt_fait.getText();
                String res = txt_fait.getText();
                txt_fait.setText(code + valeur_fait);
                
                System.out.print(res);
                
            } else {
                
            }
        }
        if (rad_non.isSelected()) {
            
            txt_fait.setText(txt_fait.getText());
            txt_fait.setText("se_trouve(" + txt_persone + "," + lieu_persone + "," + date_loc + "). \n"
                    + "jaloux(" + txt_persone + "," + txt_jalou + ").\n");
        }

    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_pers.setText("");
        txt_localisation.setText("");
        txt_persJaloux.setText("");
        date_localisation.setToolTipText("");

    }//GEN-LAST:event_btn_clearActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        Arbre arb =  new Arbre(this, rootPaneCheckingEnabled);
        arb.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_clear;
    private com.k33ptoo.components.KButton btn_ok;
    private com.k33ptoo.components.KButton btn_verifier;
    private com.toedter.calendar.JDateChooser date_localisation;
    private com.toedter.calendar.JDateChooser date_vole;
    private inspecter.expert.Header header1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JRadioButton rad_non;
    private javax.swing.JRadioButton rad_oui;
    private javax.swing.JTextArea txt_fait;
    private javax.swing.JTextField txt_localisation;
    private javax.swing.JTextField txt_pers;
    private javax.swing.JTextField txt_persJaloux;
    private javax.swing.JTextField txt_vict;
    private javax.swing.JTextField txt_vol;
    // End of variables declaration//GEN-END:variables
}
